### ISSUE TITLE
mfcc advanced example doesn't work

### ISSUE THREAD

**Issue by tremblap** [flucoma/learn-website#350]
from this page:

https://learn.flucoma.org/reference/mfcc/

clicking on the interactive demo link gives us the Uh ho message. reloading that page gives us the right page... strange....

**Comment by tedmoore** [comment]
Just was poking around here again, so bump on this!

**Comment by jamesb93** [comment]
Ooh yeah. Let me fix this...

**Comment by jamesb93** [comment]
Done

32e2dd5

**Comment by tedmoore** [comment]
This still isn't working? I just tried to navigate it and got the same issue. I'm on Chrome 104.0.5112.79 (latest version)

**Comment by jamesb93** [comment]
I would suspect you are navigating to it via an anchor and not directly? Because https://learn.flucoma.org/reference/mfcc/explain/ works if you go there right now...

**Comment by jamesb93** [comment]
Yes indeed that's the behaviour. I fixed it by bypassing the SvelteKit router for that link and instead deferring back to the browser to handle navigation with `sveltekit:reload`. Solved via c87fd10.

**Comment by tedmoore** [comment]
🙏
